[destination.filesystem]
bucket_url = "s3://bluesky-api/raw-data/" # replace with your bucket name,

[destination.filesystem.credentials]
aws_access_key_id = "AKIAQFJW6KJNUYFBFKQK" # copy the access key here
aws_secret_access_key = "k8glh8oWJXmrn1UzQmO9ci7Bnq+R/65ggRBnERAQ" # copy the secret access key here